article/urls.py
from django.urls import path

from article import views

app_name = 'article'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.update_article, name='article_update'),
    path('search/', views.search_articles, name='search_articles'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import article
from article.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
    # path('', index, name='index'),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comments.urls', namespace='comment'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
<!-- 载入静态文件 -->
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>应急知识宣传系统</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="icon" href="{% static 'Untiled Goose Game.ico' %}">
    <link rel="stylesheet" href={% static 'edit.css' %}>
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="{% static 'register.css' %}">
    <link rel="stylesheet" href="{% static 'carsoul.css' %}">
    <link rel="stylesheet" href="{% static 'float_button.css' %}">
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .back-to-top {
            position: fixed; /* 固定位置 */
            bottom: 60px; /* 距离底部的距离 */
            right: 20px; /* 距离右侧的距离 */
            z-index: 99; /* 确保按钮在最上层 */
            width: 50px;
            height: 50px;
            border-radius: 50%;
            background-color: #3498db;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            cursor: pointer;
            opacity: 0.7;
            visibility: hidden; /* 默认隐藏，当滚动时显示 */
            transition: opacity 0.3s, visibility 0.3s;
        }

        .back-to-top:hover {
            opacity: 1;
        }

        /* 当页面滚动到一定距离时显示按钮 */
        body.scroll-active .back-to-top {
            visibility: visible;
        }

        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -40px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
</head>

<body>

<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
<div id="wrapper" class="wrapper">
    {% block content %}{% endblock content %}
    <div id="push"></div>
</div>
<button id="backToTopBtn" class="back-to-top" title="返回顶部" onclick="scrollToTop()">
    <i class="fa fa-chevron-up"></i> <!-- 使用Font Awesome图标或其他图标库 -->
</button>
<!-- 引入注脚 -->
{% include 'footer.html' %}

<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

<!-- 2020.07.22: popper.js 更新为远程调用的形式 -->
{#<script src="{% static 'popper/popper-1.14.4.js' %}"></script>#}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- 引入layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>

{% block script %}{% endblock script %}


<style>

</style>

<script>
    function scrollToTop() {
        window.scrollTo({
            top: 0,
            behavior: 'smooth' // 平滑滚动效果
        });
    }

    // 监听滚动事件，当用户滚动时改变按钮的可见性
    window.addEventListener('scroll', function () {
        document.body.classList.toggle('scroll-active', window.scrollY > 200);
    });
</script>

</body>

</html>

templates/footer.html
{% load static %}
<style>
    .tooltip-inner {
        max-width: none !important; /* 调整工具提示内容的最大宽度 */
    }

    .link-item {
        border-right: 1px solid #ccc; /* 添加右侧竖线 */
        padding-right: 10px; /* 右侧内边距 */
    }

    .link-item:last-child {
        border-right: none; /* 最后一个链接去掉右侧边框 */
    }
</style>
<!-- Footer -->
<div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-2 link-item" align="center">
                友情链接：
            </div>
            <div class="col-2 link-item" align="center">
                <a href="https://www.cac.gov.cn/" data-toggle="tooltip" title="链接1">央视新闻</a>
            </div>
            <div class="col-2 link-item" align="center">
                <a href="https://www.mem.gov.cn/index.shtml" data-toggle="tooltip" title="链接2">应急管理部</a>
            </div>
            <div class="col-2 link-item" align="center">
                <a href="http://yjt.shanxi.gov.cn/" data-toggle="tooltip" title="链接3">山西省应急管理厅</a>
            </div>
            <div class="col-2 link-item" align="center">
                <a href="http://www.moe.gov.cn/" data-toggle="tooltip" title="链接4">教育部</a>
            </div>
            <div class="col-2" align="center">
                <a href="https://www.cac.gov.cn/" data-toggle="tooltip" title="链接5">网信办</a>
            </div>
        </div>
    </div>
</div>
<style>
    .logo-link {
        display: flex;
        align-items: center;
        margin-right: 10px; /* 间距，根据需求调整 */
    }

    .logo-link:last-child {
        margin-right: 0; /* 移除最后一个链接的右边距 */
    }

    .logo-img {
        /* 限制图片大小，例如设置为32x32像素 */
        width: 32px;
        height: 32px;
        /* 如果需要，可以添加其他图片样式，如边框、圆角等 */
    }

    .logo-beian {
        /* 限制图片大小，例如设置为32x32像素 */
        width: 20px;
        height: 20px;
        /* 如果需要，可以添加其他图片样式，如边框、圆角等 */
    }

    .logo-text {
        /* 放大文字，并设置为白色 */
        font-size: 16px; /* 根据需要调整字体大小 */
        color: #fff; /* 设置为白色 */
        /* 如果需要，可以添加其他文字样式，如字体、行高等 */
        margin-left: 5px; /* 根据需要调整文字与图片之间的间距 */
    }

    /* 添加或修改以下CSS规则 */
    .navbar-nav {
        display: flex;
        justify-content: center; /* 水平居中对齐 */
        flex-direction: column; /* 如果希望垂直居中，则使用此行，并且可能需要调整外部容器的高度 */
        list-style-type: none;
        padding-inline-start: 0; /* 移除默认的左内边距 */
    }

    /* 如果需要保持水平布局并居中 */
    .navbar-nav.horizontal {
        flex-direction: row;
        justify-content: center;
    }
</style>
<footer class="py-3 bg-dark sticky-bottom">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <p class="m-0 text-center text-white" align="center">晋ICP证05000465号 <img
                src="https://dimon0000000.github.io/img/police_beian.png" class="logo-beian"> 晋公网安备 14010902001579号
        </p>
        <div class="d-flex justify-content-center mt-3">
            <a href="https://dimon0000000.github.io/" class="d-flex align-items-center logo-link">
                <img src="{% static 'img/ico/博客.png' %}" alt="个人博客" class="mr-2 logo-img">
                <span class="logo-text">个人博客</span>
            </a>
            <a href="https://space.bilibili.com/291003955?spm_id_from=333.1007.0.0"
               class="d-flex align-items-center logo-link">
                <img src="{% static 'img/ico/哔哩哔哩.png' %}" alt="哔哩哔哩" class="mr-2 logo-img">
                <span class="logo-text">哔哩哔哩</span>
            </a>
            <a href="https://www.instagram.com/endless_developy/" class="d-flex align-items-center logo-link">
                <img src="{% static 'img/ico/instgram.png' %}" alt="Ins" class="mr-2 logo-img">
                <span class="logo-text">Instagram</span>
            </a>
            <a href="https://codeforces.com/profile/Developy" class="d-flex align-items-center logo-link">
                <img src="{% static 'img/ico/codeforces.png' %}" alt="CodeForces" class="mr-2 logo-img">
                <span class="logo-text">CodeForces</span>
            </a>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
<style>
    .avatar-thumb {
        width: 30px;
        height: 30px;
        object-fit: cover;
    }

    .navbar-white {
        color: #ffffff;
    }

    .imgs {
        width: 90px;
        height: 90px;
    }

    .clocks {
        color: black;
    }
    .icon {
        max-height: 40px;
        max-width: 40px;
    }
    .banners {
        max-height: 25%;
    }
    .navbar-nav .nav-item {
        display: flex;
        align-items: center;
    }
</style>

<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand d-flex align-items-center" href="{% url 'article:article_list' %}">
            <img src="{% static 'img/ico/steam.png' %}" alt="商标" class="mr-2 logo-img">
            应急管理宣传系统
        </a>

        <!-- 导航入口 -->
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <!-- 条目 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">主页💾</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="newsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        新闻📰
                    </a>
                    <div class="dropdown-menu" aria-labelledby="newsDropdown">
                        <a class="dropdown-item" href="{% url 'article:search_articles' %}?tag=应急要闻">应急要闻</a>
                        <a class="dropdown-item" href="{% url 'article:search_articles' %}?tag=时政专栏">时政专栏</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'article:search_articles' %}?tag=媒体信息">媒体信息</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="opennessDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        公开🗃️
                    </a>
                    <div class="dropdown-menu" aria-labelledby="opennessDropdown">
                        <a class="dropdown-item" href="{% url 'article:search_articles' %}?tag=通知公告">通知公告</a>
                        <a class="dropdown-item" href="{% url 'article:search_articles' %}?tag=政策解读">政策解读</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:search_articles' %}">应急科普📚︎</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">|</a>
                </li>
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0" action="{% url 'article:search_articles' %}">
                        <input type="text" class="form-control mr-sm-2" name="search" placeholder="搜索文章..." required>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link">|</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown d-flex align-items-center">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if user.profile.avatar %}
                                <img src="{{ user.profile.avatar.url }}" class="avatar-img avatar-thumb mr-2"
                                     alt="User Avatar">
                                {{ user.username }}
                            {% else %}
                                <!-- 如果用户未登录，可以显示默认的占位符或者提示 -->
                                <i class="fas fa-user-circle mr-2"></i> {{ user.username }}
                            {% endif %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>编辑资料</a>
                            <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
    <form
        style="display:none;"
        id="user_delete"
        action="{% url 'userprofile:delete' user.id %}"
        method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
{% endif %}