article/urls.py
from django.urls import path

from article import views

app_name = 'article'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.update_article, name='article_update'),
    path('search/', views.search_articles, name='search_articles'),
]

comments/urls.py
from django.urls import path

from comments import views

app_name = 'comments'

urlpatterns = [
    # 已有代码，处理一级回复
    path('post-comment/<int:article_id>', views.post_comment, name='post_comment'),
    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import article
from article.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
    # path('', index, name='index'),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comments.urls', namespace='comment'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from PIL import Image


# Create your models here.

class ArticleColumn(models.Model):
    """
    栏目的 Model
    """
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Article(models.Model):
    title = models.CharField(max_length=200)
    tags = TaggableManager(blank=True)
    avatar = models.ImageField(upload_to='avatars/%Y%m%d/', blank=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    total_views = models.PositiveIntegerField(default=0)
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    column = models.ForeignKey(ArticleColumn, null=True, blank=True,
                               on_delete=models.CASCADE,
                               related_name='article'
                               )

    def save(self, *args, **kwargs):
        article = super(Article, self).save(*args, **kwargs)

        # 固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.Resampling.LANCZOS)
            resized_image.save(self.avatar.path)

        return article

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

        # 保存时处理图片

article/views.py
import markdown
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from article.form import ArticleForm
from article.models import Article, ArticleColumn
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q

from comments.models import Comment
from userprofile.models import Profile
from PIL import Image
import re


# Create your views here.


def index(request):
    return HttpResponse("Hello, World")


def search_articles(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')


    # 初始化查询集
    article_list = Article.objects.all()

    # 搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(content__icontains=search)
        )
    else:
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)
    else: column = ''

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])
    else: tag = ''

    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }

    return render(request, 'article/search.html', context)


def article_list(request):
    # 从 url 中提取查询参数
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = Article.objects.all()

    # 搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(content__icontains=search)
        )
    else:
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 50)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 需要传递给模板（templates）的对象
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }

    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = Article.objects.get(id=id)
    comments = Comment.objects.filter(article=id)
    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.content = md.convert(article.content)

    context = {'article': article, 'toc': md.toc, 'comments': comments}

    return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)

            new_article.author = User.objects.get(id=request.user.id)
            # 新增的代码
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            form.save_m2m()
            return redirect('article:article_list')
        else:
            return HttpResponse("Error")
    else:
        form = ArticleForm()
        columns = ArticleColumn.objects.all()
        context = {'form': form, 'columns': columns}
        return render(request, 'article/create.html', context)


def article_delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('article:article_list')


def article_safe_delete(request, id):
    if request.method == 'POST':
        article = Article.objects.get(id=id)
        article.delete()
        return redirect('article:article_list')
    else:
        return HttpResponse("POST ONLY")


@login_required(login_url='/userprofile/login/')
def update_article(request, id):
    article = Article.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article.title = request.POST['title']
            article.content = request.POST['content']
            # 新增的代码
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')

                # 修改的部分
            tags_str = request.POST.get('tags')
            # 使用逗号作为分隔符来拆分标签字符串
            tags_list = [tag.strip() for tag in tags_str.split(',') if tag.strip()]
            # 设置标签
            article.tags.set(tags_list, clear=True)
            article.save()
            return redirect('article:article_detail', id=id)
        else:
            return HttpResponse("Error")
    else:
        form = ArticleForm()
        # 新增及修改的代码
        columns = ArticleColumn.objects.all()
        context = {
            'article': article,
            'article_post_form': form,
            'columns': columns,
            'tags': ','.join([x for x in article.tags.names()]),
        }
        return render(request, 'article/update.html', context)

templates/article/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    写文章
{% endblock title %}
{% block content %}
    <style>
        .body{
            background-color: white;
        }
        .article-container {
            display: flex;
            justify-content: center;
            align-items: stretch;
            margin-top: 20px;
        }

        .editor,
        .preview {
            flex: 1;
            padding: 20px;
        }

        .preview {
            border-left: 1px solid #ccc;
            background-color: #f8f8f8;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            overflow-y: auto;
            max-height: 750px; /* 添加最大高度 */
        }

        textarea {
            width: 100%;
            height: 100%;
            border: none;
            outline: none;
            resize: none;
        }

        .preview-content {
            padding: 20px;
            font-size: 16px;
            line-height: 1.6;
        }

        .preview-text {
            color: #333;
        }

        .preview-text em {
            font-style: italic;
        }

        .preview-text strong {
            font-weight: bold;
        }

        .preview-text a {
            color: #007bff;
            text-decoration: none;
        }

        .preview-text a:hover {
            text-decoration: underline;
        }

        .preview-animation {
            animation: fadeIn 1s ease-out;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        .form-container {
            /* 根据需要添加其他样式 */
        }

        .form-row {
            display: flex;
            justify-content: space-between; /* 如果需要元素之间有间隔 */
            align-items: center; /* 垂直居中对齐 */
        }

        .form-group {
            /* 可能需要调整margin或padding以适应新的布局 */
            flex: 1; /* 如果希望元素等宽 */
            margin-right: 10px; /* 可选，用于元素之间的间隔 */
        }

        /* 如果需要，可以为最后一个form-group添加特殊样式以移除右边距 */
        .form-row .form-group:last-child {
            margin-right: 0;
        }
    </style>
    <div class="article-container">
        <div class="preview" id="markdown-preview">
            <div class="preview-content">
                <p class="preview-text preview-animation">这里是实时预览区域。</p>
                <p class="preview-text preview-animation">您可以在右侧编辑区域输入 Markdown
                    代码，并在此处查看实时渲染结果。</p>
                <p class="preview-text preview-animation">在此您可以畅所欲言</p>
                <p class="preview-text preview-animation">祝您写作愉快😉</p>
            </div>
        </div>
        <div class="editor">
            <h2 align="center">文章书写</h2>
            <p align="center">本文支持Markdown语法，点击<a href="https://markdown.com.cn/basic-syntax/">🔗</a>访问Markdown基本语法教程
            </p>
            <form method="post" action="." enctype="multipart/form-data" class="form-container">
                {% csrf_token %}
                <!-- 文章标题和栏目，使用form-row类 -->
                <div class="form-row">
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title" required
                               placeholder="在此输入您的标题">
                    </div>
                    <div class="form-group">
                        <label for="column">栏目</label>
                        <select class="form-control" id="column" name="column">
                            <option value="none">请选择栏目..</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <!-- 文章标签和标题图，使用form-row类 -->
                <div class="form-row">
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text" class="form-control" id="tags" name="tags" placeholder="请用英文逗号对标签进行分割，如: a, b, c,">
                    </div>
                    <div class="form-group">
                        <label for="avatar">标题图</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea class="form-control" id="body" name="content" rows="12" required
                              placeholder="在此输入您的正文，支持Markdown" oninput="updatePreview()"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>

    <script>
        const markdownInput = document.getElementById('body');
        const markdownPreview = document.getElementById('markdown-preview');

        markdownInput.addEventListener('input', updatePreview);

        function updatePreview() {
            const markdownText = markdownInput.value;
            markdownPreview.innerHTML = marked(markdownText);
        }
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/3.0.1/marked.min.js"></script>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    文章详情
{% endblock title %}
{% block content %}
    <style>
        .sidebar {
            will-change: min-height;
        }

        .sidebar__inner {
            transform: translate(0, 0);
            transform: translate3d(0, 0, 0);
            will-change: position, transform;
        }
    </style>
    <div class="container bkg">
        <div class="row">
            <div class="col-9">
                <!-- 标题及作者 -->
                <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
                <div class="col-12 alert alert-success">作者：{{ article.author }}
                    {% if user == article.author %}
                        · <a href="#" onclick="confirm_delete()">删除文章</a>
                        · <a href="{% url "article:article_update" article.id %}">
                        编辑文章
                    </a>
                    {% endif %}
                    <div>
                        浏览：{{ article.total_views }}
                    </div>
                    <form
                            style="display:none;"
                            id="safe_delete"
                            action="{% url 'article:article_safe_delete' article.id %}"
                            method="POST"
                    >
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>

                </div>

                <!-- 文章正文 -->
                <div class="col-12">
                    <p>{{ article.content | safe }}</p>
                </div>
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form
                                action="{% url 'comment:post_comment' article.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要发言：
                                    </strong>
                                </label>
                                <textarea
                                        type="text"
                                        class="form-control"
                                        id="body"
                                        name="body"
                                        rows="2"></textarea>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary ">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}



                <!-- 显示评论 -->
                {% load mptt_tags %}
                <h4>共有{{ comments.count }}条评论</h4>
                <div class="row">
                    <!-- 遍历树形结构 -->
                    {% recursetree comments %}
                        <!-- 给 node 取个别名 comment -->
                        {% with comment=node %}
                            <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}"
                            >
                                <hr>
                                <p>
                                    <img src="{{ comment.user.profile.avatar.url }}"
                                         class="avatar-img avatar-thumb mr-2"
                                         alt="User Avatar">
                                    <strong style="color: pink">
                                        {{ comment.user }}
                                    </strong>

                                    {% if comment.reply_to %}
                                        <i class="far fa-arrow-alt-circle-right"
                                           style="color: cornflowerblue;"
                                        ></i>
                                        <strong style="color: pink">
                                            {{ comment.reply_to }}
                                        </strong>
                                    {% endif %}

                                </p>
                                <div>{{ comment.body|safe }}</div>

                                <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                                    <!-- 加载 modal 的按钮 -->
                                    {% if user.is_authenticated %}
                                        <button type="button"
                                                class="btn btn-light btn-sm text-muted"
                                                onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                        >
                                            回复
                                        </button>
                                    {% else %}
                                        <a class="btn btn-light btn-sm text-muted"
                                           href="{% url 'userprofile:login' %}"
                                        >
                                            回复
                                        </a>
                                    {% endif %}
                                </div>

                                <!-- Modal -->
                                <div class="modal fade"
                                     id="comment_{{ comment.id }}"
                                     tabindex="-1"
                                     role="dialog"
                                     aria-labelledby="CommentModalCenter"
                                     aria-hidden="true"
                                >
                                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                        <div class="modal-content" style="height: 480px">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">
                                                    回复 {{ comment.user }}：</h5>
                                            </div>
                                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                        </div>
                                    </div>
                                </div>

                                {% if not comment.is_leaf_node %}
                                    <div class="children">
                                        {{ children }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endwith %}
                    {% endrecursetree %}
                </div>

            </div>

            <div class="sidebar" id="sidebar">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
    {% block script %}
        <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
        <script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
        <script type="text/javascript">
            $('#sidebar').stickySidebar({
                topSpacing: 20,
                bottomSpacing: 20,
            });
        </script>


        <script>
            function confirm_delete() {
                layer.open({
                    title: "确认删除",
                    content: "确认删除这篇文章吗？",
                    yes: function (index, layero) {
                        location.href = '{% url "article:article_delete" article.id %}'
                    },
                })
            }

            function confirm_safe_delete() {
                layer.open({
                    title: "确认删除",
                    content: "确认删除这篇文章吗？",
                    yes: function (index, layero) {
                        $('form#safe_delete button').click();
                        layer.close(index);
                    }
                })
            }
        </script>
    {% endblock script %}
    <script>
        // 加载 modal
        function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/post-comment/' +
                    article_id +
                    '/' +
                    comment_id +
                    '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
                $(modal_body).append(content);
            }
            ;

            $(modal_id).modal('show');
        }

        // 处理二级回复
        function post_reply_and_show_it(new_comment_id) {
            let next_url = "{% url 'article:article_detail' article.id %}";
            // 去除 url 尾部 '/' 符号
            next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
            // 刷新并定位到锚点
            window.location.replace(next_url + "#comment_elem_" + new_comment_id);
        };
    </script>

{% endblock content %}

templates/article/search.html
<style>
    .header_new {
    }
</style>
{% extends "base.html" %}
{% load static %}
{% block title %}
    查找
{% endblock title %}
{% block content %}
    {% if articles %}
        {% if tag %}
            <h2 class="header_new" align="center">{{ tag }}</h2>
        {% elif tag == Node %}
            <h2 class="header_new" align="center">应急科普</h2>
        {% else %}
            <h2 class="header_new" align="center">应急科普</h2>
        {% endif %}
    {% else %}
        <h2 align="center">暂无相关文章</h2>
    {% endif %}
    <div class="container">
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}

        <!-- 列表循环 -->
        <div class="row mt-2">
            {% for article in articles %}
                <!-- 标题图 -->
                {% if article.avatar %}
                    {#                    使用Bootstrap的栅格系统来排列。每个格栅由12个小格栅组成#}
                    <div class="col-3">
                        <img src="{{ article.avatar.url }}"
                             alt="avatar"
                             style="max-width:100%; border-radius: 20px; max-height: 75%"
                        >
                    </div>
                    <div class="col-9">
                {% else %}
                    <div class="col-12">
                {% endif %}
            <!-- 栏目 -->
            {% if article.column %}
                <button type="button"
                        class="btn btn-sm mb-2
                        {% if article.column.title == '算法竞赛' %}
                            btn-success
                        {% elif article.column.title == '应急管理' %}
                            btn-danger
                        {% elif article.column.title == '测试文章' %}
                            btn-warning
                        {% elif article.column.title == '政策解读' %}
                            btn-light
                        {% elif article.column.title == '时政专栏' %}
                            btn-dark
                        {% elif article.column.title == '通知公告' %}
                            btn-outline-danger
                        {% endif %}
                    "
                >
                    {{ article.column }}
                </button>
            {% endif %}

            <!-- 标签 -->
            <span>
                        {% for tag in article.tags.all %}
                            <a href="{% url 'article:search_articles' %}?tag={{ tag }}"
                               class="badge badge-secondary"
                            >
                            {{ tag }}
                             </a>
                        {% endfor %}
                    </span>
            <!-- 标题 -->
            <h4>
                <b>
                    <a href="{% url 'article:article_detail' article.id %}"
                       style="color: black;"
                    >
                        {{ article.title }}
                    </a>
                </b>
            </h4>

            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ article.content|slice:'100' }}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 附加信息 -->
                <span>
        <i class="fas fa-eye" style="color: lightskyblue;"></i>
        {{ article.total_views }}&nbsp;&nbsp;&nbsp;
    </span>
                <span>
        <i class="fas fa-comments" style="color: yellowgreen;"></i>
                    <!-- 修改为评论的计数 -->
        {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
    </span>
                <span>
        <i class="fas fa-clock" style="color: pink;"></i>
        {{ article.updated|date:'Y-m-d' }}
    </span>
            </p>
            <hr>
            </div>
            {% endfor %}
            </div>


            <!-- 页码导航 -->
            <div class="pagination row">
                <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-success"
                    >
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}